// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package try_gqlgen

type NewTodo struct {
	UserID string `json:"userID"`
	Text   string `json:"text"`
}

type NewUser struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
